# Generated by Django 3.0.6 on 2020-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='meal',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100),
        ),
    ]
