# Generated by Django 3.0.6 on 2020-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200505_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
