# Generated by Django 3.0.6 on 2020-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200505_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='day_of_the_week',
            field=models.CharField(choices=[('Mondat', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
    ]
