# Generated by Django 3.0.6 on 2020-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200505_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(),
        ),
    ]
