# Generated by Django 3.0.6 on 2020-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200506_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
    ]
