# Generated by Django 3.0.6 on 2020-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200506_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
